version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: pilates-postgres
    environment:
      POSTGRES_USER: pilates
      POSTGRES_PASSWORD: pilatespass
      POSTGRES_DB: pilates_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
